; [pytest]
; addopts = -v
; testpaths = tests
; markers =
;     ui: UI browser automation tests (Playwright)
;     api: API endpoint tests (requests)

[pytest]
addopts = -v  --headed
testpaths = tests
markers =
    ui: UI browser automation tests 
    api: API endpoint tests 
    qase: Qase test case mapping
