[pytest]
addopts = -v
testpaths = tests
markers =
    login: Combined UI + API tests for Login module
    upload: Combined UI + API tests for Upload module
    creation: Combined UI + API tests for Creation module
    delete: Combined UI + API tests for Delete module
    rename: Combined UI + API tests for Rename module
    move: Combined UI + API tests for Move module
    trash: Combined UI + API tests for Trash module
    qase: Qase test case mapping
